### ISSUE TITLE
Terminal_Set() constructor issue

### ISSUE THREAD

**Issue by omidr1370** [AwardOfSky/TensorGP#1]
Hello. Thanks for this Tensorial approach. I have one question.
It seems "Terminal_Set()" constructor is not working. I want to define four 2x2 tensors in my terminal. I'll be grateful if you let me know the correct syntax to define the terminal.

   def` calc_fit(**kwargs):
    # read parameters
    population = kwargs.get('population')
    generation = kwargs.get('generation')
    tensors = kwargs.get('tensors')
    f_path = kwargs.get('f_path')
    _stf = kwargs.get('stf')
    target = kwargs.get('target')

    fn = f_path + "gen_" + str(generation).zfill(5)
    fitness = []
    times = []
    best_ind = 0

    # set objective function according to min/max
    fit = 0
    condition = lambda: (fit < max_fit)  # minimizing
    max_fit = float('inf')

    for i in range(len(tensors)):

        start_ind = time.time()
        fit = tf_rmse(tensors[i], target).numpy()

        if condition():
            max_fit = fit
            best_ind = i

        times.append((time.time() - start_ind) * 1000.0)
        fitness.append(fit)
        population[i]['fitness'] = fit

    #if generation == gens:
    #    save_image(tensors[best_ind], best_ind, fn, 2)

    return` population, population[best_ind]`

# Different types of function sets

`normal_set = {'add', 'sub'}`

`if __name__ == "__main__":`

    # GP params
    dev = '/gpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 250 
    pop_size = 2500  
    tour_size = 3
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 10
    max_init_depth = 10
    elite_size = 1 # 0 to turn off
    runs = 1 # Number of average runs

    # problems
    optimal_solution = tf.convert_to_tensor(F)   #F is a (19828, 2, 2) tensor

   # terminal
   indexing_variables = 3
   domain_range = [19828, 2, 2] 
   my_terminal_set = Terminal_set(indexing_variables, domain_range)
   my_terminal_set.add_to_set("T_1", tf.convert_to_tensor(T_1, shape=(19828, 2, 2)))
   my_terminal_set.add_to_set("T_2", tf.convert_to_tensor(T_2, shape=(19828, 2, 2)))
   my_terminal_set.add_to_set("T_3", tf.convert_to_tensor(T_3, shape=(19828, 2, 2)))
   my_terminal_set.add_to_set("T_4", tf.convert_to_tensor(T_4, shape=(19828, 2, 2)))

   problems = [optimal_solution]  # Add to run more problems

    # Domains dimensions
    test_cases = [[19828, 2, 2]]

    for p in problems:
        

        for res in test_cases:
            
            for r in range(runs):
                
                #seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482 # reproducibility
                
                # create engine
                engine = Engine(terminal_set=my_terminal_set,
                                fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                max_tree_depth=max_tree_dep,
                                target_dims=res,
                                target=optimal_solution,
                                #elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimizing',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=2,
                                min_domain=-0.5,
                                max_domain=0.5,
                                operators=normal_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=False,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)

                # run evolutionary process
                engine.run()

error:

`NameError: name 'Terminal_set' is not defined`

**Comment by AwardOfSky** [comment]
Hello @omidr1370, thanks for your interest. The correct method is called `Terminal_Set` not `Terminal_set`.
I understand why you made that error as there was a typo in the readme. It's fixed now.
Thanks for the feedback!

**Comment by omidr1370** [comment]
Thanks. It seems it solved my problem. However, I still have some difficulties defining the terminal. I have the target "F" which is a tensor with shape (19828, 2, 2). I want to define four tensors(T_1,T_2,T_3,T_4) with the same shape like the target(19828, 2, 2). I receive an error. I really appreciate your help if you let me know the correct set-up for such a problem. Below is my code:

def calc_fit(**kwargs):
    # read parameters
    population = kwargs.get('population')
    generation = kwargs.get('generation')
    tensors = kwargs.get('tensors')
    f_path = kwargs.get('f_path')
    _stf = kwargs.get('stf')
    target = kwargs.get('target')

    fn = f_path + "gen_" + str(generation).zfill(5)
    fitness = []
    times = []
    best_ind = 0

    # set objective function according to min/max
    fit = 0
    condition = lambda: (fit < max_fit)  # minimizing
    max_fit = float('inf')

    for i in range(len(tensors)):

        start_ind = time.time()
        fit = tf_rmse(tensors[i], target).numpy()

        if condition():
            max_fit = fit
            best_ind = i

        times.append((time.time() - start_ind) * 1000.0)
        fitness.append(fit)
        population[i]['fitness'] = fit

    #if generation == gens:
    #    save_image(tensors[best_ind], best_ind, fn, 2)

    return population, population[best_ind]

normal_set = {'add', 'sub'}








if __name__ == "__main__":

    # GP params
    dev = '/gpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 250 
    pop_size = 2500  
    tour_size = 3
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 10
    max_init_depth = 10
    elite_size = 1 # 0 to turn off
    runs = 1 # Number of average runs

    # problems
    optimal_solution = tf.convert_to_tensor(F) #F is a (19828, 2, 2) tensor
    optimal_solution = tf.cast(optimal_solution, tf.float32)

    indexing_variables = 3
    domain_range = [19828, 2, 2]
    my_terminal_set = Terminal_Set(indexing_variables, domain_range)
    my_terminal_set.add_to_set("T_1", T_1)  # T_1 is a (19828, 2, 2)  tensor
    my_terminal_set.add_to_set("T_2", T_2)  # T_2 is a (19828, 2, 2)  tensor
    my_terminal_set.add_to_set("T_3", T_3)  # T_3 is a (19828, 2, 2)  tensor
    my_terminal_set.add_to_set("T_4", T_4)  # T_4 is a (19828, 2, 2)  tensor

    problems = [optimal_solution] # Add to run more problems







    # Domains dimensions
    test_cases = [[19828, 2, 2]]

    for p in problems:
    

        for res in test_cases:
        
            for r in range(runs):
            
                #seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482 # reproducibility
            
                # create engine
                engine = Engine(uniform_scalar_prob=0,
                                terminal_set=my_terminal_set,
                                fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                max_tree_depth=max_tree_dep,
                                target_dims=res,
                                target=optimal_solution,
                                #elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimizing',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=3,
                                min_domain=-0.5,
                                max_domain=0.5,
                                operators=normal_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=False,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)

                # run evolutionary process
                engine.run()


Error:

KeyError: 'T'

**Comment by AwardOfSky** [comment]
Hello @omidr1370. I tried to emulate your setup and had no problems but I don't know how you are defining the tensors you provide. If I had to guess you may be missing a conversion to tensor where you define the terminals:
Try this:


```python
my_terminal_set.add_to_set("T_1", tf.convert_to_tensor(T_1, tf.float32))
my_terminal_set.add_to_set("T_2", tf.convert_to_tensor(T_2, tf.float32))
my_terminal_set.add_to_set("T_3", tf.convert_to_tensor(T_3, tf.float32))
my_terminal_set.add_to_set("T_4", tf.convert_to_tensor(T_4, tf.float32))
```

If this fails to solve your issue, I would appreciate if you posted the full traceback of the error to see where the program crashes.

**Comment by omidr1370** [comment]
Hello. Thank you so much for your help. I already converted tensors before using them in the terminal. My problem still remains and I receive an error. It runs only for the first iteration. I use "Jupyter Notebook" and import everything. I put the error at the end of this text.
So, I will explain everything with one more question for better clarification. Perhaps, it will help to find a solution easier. First, I have five tensors, "F" which is the target, and "T_1","T_2","T_3","T_4" which I want to use in my terminal. All these tensors have the same shape of (19828, 2, 2). My goal is to get an equation in this form:
F= C1T_1+C2T_2+C3T_3+C4T_4. 
Here C1,.....,C4 are constants. As I don't want any constants to appear alone(C1T_1+C2T_2+C3T_3+C4T_4+**C5**), I put "uniform_scalar_prob=0". Each of these tensors has 19828 data points which consist of 2x2 tensors. For example, T_1[0]=array([[ 0.10702974,  1.9503768 ],[ 1.9503768 , -0.10702974]]). Moreover, I don't want two tensors multiplied by each other. So, I use only addition(add) and substraction(sub) for my "operators".

I'm not sure about these options for my problem. Did I put these correctly?
indexing_variables = ? 3
domain_range = ?  [19828, 2, 2]

### Here is the error:


Device /cpu:0 successfully tested, using this device.  
Engine seed: 39485793482 

[ gen,   fit avg,   fit std,  fit best,   dep avg,   dep std,  dep best,   nod avg,   nod std,  nod best]
 
[   0,  1.334728,  0.399250,  0.001294,     5.874,  2.650684,         2,   278.814, 498.216824,         7] 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-205-d3e42ef402e1> in <module>
    125 
    126                 # run evolutionary process
--> 127                 engine.run()

C:\TensorGP-master\tensorgp\engine.py in run(self)
   1290 
   1291             # calculate fitness of the new population
-> 1292             new_population, _new_best = self.fitness_func_wrap(population=new_population,
   1293                                                                f_path=self.experiment.current_directory)
   1294             # update best and population

C:\TensorGP-master\tensorgp\engine.py in fitness_func_wrap(self, population, f_path)
    999         if self.debug > 4: print("\nEvaluating generation: " + str(self.current_generation))
   1000         with tf.device(self.device):
-> 1001             tensors, time_taken = self.calculate_tensors(population)
   1002         if self.debug > 4: print("Calculated " + str(len(tensors)) + " tensors in (s): " + str(time_taken))
   1003 

C:\TensorGP-master\tensorgp\engine.py in calculate_tensors(self, population)
    979             #_start = time.time()
    980 
--> 981             test_tens = p['tree'].get_tensor(self)
    982             tens = self.final_transform_domain(test_tens)
    983             tensors.append(tens)

C:\TensorGP-master\tensorgp\engine.py in get_tensor(self, engref)
    294             tens_list = []
    295             for c in self.children:
--> 296                 tens_list.append(c.get_tensor(engref))
    297 
    298             return self.node_tensor(tens_list, engref)

C:\TensorGP-master\tensorgp\engine.py in get_tensor(self, engref)
    294             tens_list = []
    295             for c in self.children:
--> 296                 tens_list.append(c.get_tensor(engref))
    297 
    298             return self.node_tensor(tens_list, engref)

C:\TensorGP-master\tensorgp\engine.py in get_tensor(self, engref)
    290 
    291             else:
--> 292                 return engref.terminal.set[self.value]
    293         else:
    294             tens_list = []

KeyError: 'T'

**Comment by AwardOfSky** [comment]
Hey again @omidr1370. 
There was an error in the method for replacing modes in point mutation when the terminals had more than 1 character. It's fixed now.
Once again thanks for your patience and feedback!
Let me know if you have any more problems.

PS: the only file that I updated was engine.py in the tensorgp folder.

**Comment by omidr1370** [comment]
Thank you so much. It works. 
Now, I want to define my own operators for my problem. I receive an error in "Function_Set". I put my code and the error below:

### code:

def calc_fit(**kwargs):
    # read parameters
    population = kwargs.get('population')
    generation = kwargs.get('generation')
    tensors = kwargs.get('tensors')
    f_path = kwargs.get('f_path')
    _stf = kwargs.get('stf')
    target = kwargs.get('target')

    fn = f_path + "gen_" + str(generation).zfill(5)
    fitness = []
    times = []
    best_ind = 0

    # set objective function according to min/max
    fit = 0
    condition = lambda: (fit < max_fit)  # minimizing
    max_fit = float('inf')

    for i in range(len(tensors)):

        start_ind = time.time()
        fit = tf_rmse(tensors[i], target).numpy()

        if condition():
            max_fit = fit
            best_ind = i

        times.append((time.time() - start_ind) * 1000.0)
        fitness.append(fit)
        population[i]['fitness'] = fit

    #if generation == gens:
    #    save_image(tensors[best_ind], best_ind, fn, 2)

    return population, population[best_ind]



def node_add(child1, child2, dims=[]):           #only two tensors will be added to each other
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.add(child1, child2)
    else:
        return tf.constant(0,dtype=tf.float32)


def node_sub(child1, child2, dims=[]):          #only two tensors will be substracted
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.subtract(child1, child2)
    else:
        return tf.constant(0,dtype=tf.float32)


def node_mult(child1, child2, dims=[]):        #only a tensor and a scalar will be multiplied
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.constant(0,dtype=tf.float32)
    elif len(tf.shape(child1))==0 and len(tf.shape(child2))==0:
        return tf.constant(0,dtype=tf.float32)
    else:
        return tf.convert_to_tensor(child1*child2, dtype=tf.float32)















if __name__ == "__main__":

    # GP params
    dev = '/cpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 50 
    pop_size = 1000  
    tour_size = 3
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 10
    max_init_depth = 10
    elite_size = 1 # 0 to turn off
    runs = 1 # Number of average runs

    # problems
    optimal_solution = tf.convert_to_tensor(F) #F is a (19828, 2, 2) tensor
    optimal_solution = tf.cast(optimal_solution, tf.float32)

    indexing_variables = 3
    domain_range = [797,2,2]
    my_terminal_set = Terminal_Set(indexing_variables, domain_range)
    my_terminal_set.add_to_set("T_1", tf.convert_to_tensor(T_1, tf.float32))
    my_terminal_set.add_to_set("T_2", tf.convert_to_tensor(T_2, tf.float32))
    my_terminal_set.add_to_set("T_3", tf.convert_to_tensor(T_3, tf.float32))
    my_terminal_set.add_to_set("T_4", tf.convert_to_tensor(T_4, tf.float32))
    my_terminal_set.remove_from_set("x")
    my_terminal_set.remove_from_set("y")
    my_terminal_set.remove_from_set("z")
    
    
    # Define subset of internally implemented operators
    primitives = {'add', 'sub', 'mult', 'div'}
    my_function_set = Function_Set(primitives)

    # Add rmse_node, which has 2 arguments with name "rmse"
    my_function_set.add_to_set("node_add", 2, node_add)
    my_function_set.add_to_set("node_sub", 2, node_sub)
    my_function_set.add_to_set("node_mult", 2, node_mult)
    

    # You can also remove operators from the set
    my_function_set-remove_from_set("add")
    my_function_set-remove_from_set("sub")
    my_function_set-remove_from_set("mult")
    my_function_set-remove_from_set("div")
    





    problems = [optimal_solution] # Add to run more problems







    # Domains dimensions
    test_cases = [[797,2,2]]


    for p in problems:
    

        for res in test_cases:
        
            for r in range(runs):
            
                #seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482 # reproducibility
            
                # create engine
                engine = Engine(uniform_scalar_prob=0,
                                scalar_prob=0.55,
                                terminal_prob=0.2,
                                terminal_set=my_terminal_set,
                                fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                max_tree_depth=max_tree_dep,
                                target_dims=res,
                                target=optimal_solution,
                                #elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimizing',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=3,
                                min_domain=-0.25,
                                max_domain=0.25,
                                operators=my_function_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=True,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)

                # run evolutionary process
                engine.run()

### Error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-102-811c75aff0ea> in <module>
    106     # Define subset of internally implemented operators
    107     primitives = {'add', 'sub', 'mult', 'div'}
--> 108     my_function_set = Function_Set(primitives)
    109 
    110     # Add rmse_node, which has 2 arguments with name "rmse"

TypeError: __init__() missing 2 required positional arguments: 'fset' and 'edim'

**Comment by AwardOfSky** [comment]
Hello @omidr1370. First and foremost sorry for the delayed response, I have been quite busy.

In the function set you should define the number of variables you want to index, as you did for the engine constructor.
However, by defining the function set the parameter that you want to define is `function_set` not `operators`. Again thanks for pointing this out to me because it was also wrong in the readme.

So what you do is 
```Python
my_function_set = Function_Set(primitives, indexing_variables)
```

and then:
```Python
engine = Engine(function_set=my_function_set,
		... # other parameters,
		)
engine.run()
```



To leave out any doubts, below I will post an example of a working code based on yours:

```Python
    # GP params
    dev = '/cpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 50
    pop_size = 1000
    tour_size = 3
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 10
    max_init_depth = 10
    elite_size = 1  # 0 to turn off
    runs = 1  # Number of average runs

    # problems
    optimal_solution = tf.convert_to_tensor(F)  # F is a (19828, 2, 2) tensor
    optimal_solution = tf.cast(optimal_solution, tf.float32)

    indexing_variables = 3
    domain_range = [797, 2, 2]
    my_terminal_set = Terminal_Set(indexing_variables, domain_range)
    my_terminal_set.add_to_set("T_1", tf.convert_to_tensor(T_1, tf.float32))
    my_terminal_set.add_to_set("T_2", tf.convert_to_tensor(T_2, tf.float32))
    my_terminal_set.add_to_set("T_3", tf.convert_to_tensor(T_3, tf.float32))
    my_terminal_set.add_to_set("T_4", tf.convert_to_tensor(T_4, tf.float32))
    my_terminal_set.remove_from_set("x")
    my_terminal_set.remove_from_set("y")
    my_terminal_set.remove_from_set("z")

    # Define subset of internally implemented operators
    primitives = {'add', 'sub', 'mult', 'div'}
    my_function_set = Function_Set(primitives, indexing_variables)

    # Add rmse_node, which has 2 arguments with name "rmse"
    my_function_set.add_to_set("node_add", 2, node_add)
    my_function_set.add_to_set("node_sub", 2, node_sub)
    my_function_set.add_to_set("node_mult", 2, node_mult)

    # You can also remove operators from the set
    my_function_set.remove_from_set("add")
    my_function_set.remove_from_set("sub")
    my_function_set.remove_from_set("mult")
    my_function_set.remove_from_set("div")


    problems = [optimal_solution]  # Add to run more problems

    # Domains dimensions
    test_cases = [[797, 2, 2]]

    for p in problems:

        for res in test_cases:

            for r in range(runs):
                # seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482  # reproducibility

                # create engine
                engine = Engine(uniform_scalar_prob=0,
                                scalar_prob=0.55,
                                terminal_prob=0.2,
                                terminal_set=my_terminal_set,
                                fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                max_tree_depth=max_tree_dep,
                                target_dims=res,
                                target=optimal_solution,
                                # elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimizing',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=3,
                                min_domain=-0.25,
                                max_domain=0.25,
                                function_set=my_function_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=True,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)

                # run evolutionary process
                engine.run()

    print("Done!")
```

PS: For future reference, the  `operators ` parameter is there for when you want to use a subset of the operators defined by the engine but you don't want to go through the hassle of defining the whole function set (this does work for custom ops like you have here). So, for instance:

```Python
ops = {'add, 'sub'}
engine = Engine(operators =ops,
		... # other parameters,
		)
engine.run()
```

would start an evolutionary run with only the standard sub and add operators defined internally by the engine.

**Comment by omidr1370** [comment]
Thank you so much for your time and clarification. I still have problem and receive an error due to "edim" inside "Function_Set" class. Do you use the same "engine.py" code? I used the same as the one you suggested but I receive the following error. Again, I am really grateful for the time you put to answer my questions.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-107-305f8c7ad63b> in <module>
    105     # Define subset of internally implemented operators
    106     primitives = {'add', 'sub', 'mult', 'div'}
--> 107     my_function_set = Function_Set(primitives, indexing_variables)
    108 
    109     # Add rmse_node, which has 2 arguments with name "rmse"

TypeError: __init__() missing 1 required positional argument: 'edim'

**Comment by AwardOfSky** [comment]
Yup, there was an outdated version of the Function Set. Should be solved now.

**Comment by omidr1370** [comment]
Thanks. Now, it's running but I can't understand why I can't see custom functions in the result. For example, these are my custom functions.

```
def node_add(child1, child2, dims=[]):           #only two tensors will be added to each other
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.add(child1, child2)
    else:
        return tf.constant(0,dtype=tf.float32)


def node_sub(child1, child2, dims=[]):          #only two tensors will be substracted
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.subtract(child1, child2)
    else:
        return tf.constant(0,dtype=tf.float32)


def node_mult(child1, child2, dims=[]):        #only a tensor and a scalar will be multiplied
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.constant(0,dtype=tf.float32)
    elif len(tf.shape(child1))==0 and len(tf.shape(child2))==0:
        return tf.constant(0,dtype=tf.float32)
    else:
        return tf.convert_to_tensor(child1*child2, dtype=tf.float32)


```

And this is my setup and the result of such setup. As you see, two tensors multiplied to each other which I don't want.

### Setup

```
    # GP params
    dev = '/cpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 25
    pop_size = 1000
    tour_size = 3
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 10
    max_init_depth = 10
    elite_size = 1  # 0 to turn off
    runs = 1  # Number of average runs

    # problems
    optimal_solution = tf.convert_to_tensor(F)  # F is a (19828, 2, 2) tensor
    optimal_solution = tf.cast(optimal_solution, tf.float32)

    indexing_variables = 3
    domain_range = [7329, 2, 2]
    my_terminal_set = Terminal_Set(indexing_variables, domain_range)
    my_terminal_set.add_to_set("T_1", tf.convert_to_tensor(T_1, tf.float32))
    my_terminal_set.add_to_set("T_2", tf.convert_to_tensor(T_2, tf.float32))
    my_terminal_set.add_to_set("T_3", tf.convert_to_tensor(T_3, tf.float32))
    my_terminal_set.add_to_set("T_4", tf.convert_to_tensor(T_4, tf.float32))
    my_terminal_set.remove_from_set("x")
    my_terminal_set.remove_from_set("y")
    #my_terminal_set.remove_from_set("z")

    # Define subset of internally implemented operators
    primitives = {'add', 'sub', 'mult', 'div'}
    my_function_set = Function_Set(primitives, indexing_variables)

    # Add rmse_node, which has 2 arguments with name "rmse"
    my_function_set.add_to_set("node_add", 2, node_add)
    my_function_set.add_to_set("node_sub", 2, node_sub)
    my_function_set.add_to_set("node_mult", 2, node_mult)

    # You can also remove operators from the set
    my_function_set.remove_from_set("add")
    my_function_set.remove_from_set("sub")
    my_function_set.remove_from_set("mult")
    my_function_set.remove_from_set("div")


    problems = [optimal_solution]  # Add to run more problems

    # Domains dimensions
    test_cases = [[7329, 2, 2]]

    for p in problems:

        for res in test_cases:

            for r in range(runs):
                # seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482  # reproducibility

                # create engine
                engine = Engine(uniform_scalar_prob=0.8,
                                scalar_prob=0,
                                terminal_prob=0.2,
                                terminal_set=my_terminal_set,
                                fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                max_tree_depth=max_tree_dep,
                                target_dims=res,
                                target=optimal_solution,
                                # elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimizing',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=3,
                                min_domain=-0.25,
                                max_domain=0.25,
                                function_set=my_function_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=True,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)

                # run evolutionary process
                engine.run()

    print("Done!")

```

Result

```
Best individual:
node_add(node_sub(T_4, T_1), node_sub(node_sub(T_4, T_3), node_add(node_add(node_mult(node_sub(T_1, T_4), node_mult(T_4, T_2)), node_sub(node_add(T_3, T_2), node_add(T_1, T_4))), T_3))) 


```

My desired form of the equation is:


C<sub>0</sub>T<sub>1</sub>+C<sub>1</sub>T<sub>2</sub>+C<sub>2</sub>T<sub>3</sub>+C<sub>3</sub>T<sub>4</sub>

which C<sub>0</sub>,C<sub>1</sub>,C<sub>2</sub> and C<sub>3</sub> are constants.

**Comment by omidr1370** [comment]
To ask my question clearly, I see my functions in the result but I can't see them working properly. For example, two tensors are multiplied by each other(T_4 and T_2) which I limited to avoid this multiplication in my custom function. Do you know the reason?
Thank you in advance for your time.

**Comment by AwardOfSky** [comment]
The functions that you define in the terminal set are the ones that are used by the engine.
Maybe I did not understand your question, but the fact that you see `node_mult(T4, T2)` in the resulting individuals does not mean that they are being multiplied, simply that your custom `node_mult` operator is being called.

I did a test with this code:

```Python
    T_1 = np.ones([797, 2, 2], np.float)
    T_2 = np.ones([797, 2, 2], np.float)
    tf_node_mult = node_mult(T_1, T_2)
    print(tf_node_mult.numpy())
```


And the result is `0.0` as expected according to your implementation of `node_mult`, because both `T_1` and `T_2 ` are rank 3 tensors.

Btw, your custom operators should always return tensors of the same shape so there are no conflicts in subsequent tensors operations
(EDIT: some TensorFlow operations between tensors of different shapes are undefined, but if you can get a working system like this, maybe it pays off with the lesser bottleneck).
Nevertheless, I would encourage you to change your `node_mult` to have the arguments as your input using the `dims` parameter (that's the use for this parameter) and only then optimize. For example, you should first do something like:

```Python
def node_mult(child1, child2, dims=[]):
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.constant(0,shape=dims,dtype=tf.float32)
    elif len(tf.shape(child1))==0 and len(tf.shape(child2))==0:
        return tf.constant(0,shape=dims,dtype=tf.float32)
    else:
        return tf.convert_to_tensor(child1*child2, dtype=tf.float32) #oh, and there is no need to explicitly convert to tensor here
```

**Comment by omidr1370** [comment]
Thank you so much for your suggestion and explanation.
There is a problem here. When I allow scalars to appear, changing the engine parameters, the prediction seems most of the time to be zero.

So, I don't want:

```
1. Two tensors or two scalars multiplied by each other.
2. Two scalars added or subtracted by each other.(The only exception is zero)
3. One tensor and one scalar added or subtracted by each other.
```
In the above situations, my code will return zero.

For example, this is the result of one of the runs:

```
node_sub(node_add(node_sub(scalar(-0.024643402271970538), T_3), node_mult(node_sub(node_mult(scalar(-0.008758578372655368), scalar(-0.05651795832957618)), node_add(T_2, T_1)), node_mult(scalar(-0.09503844302366904), scalar(-0.10830596509618018)))), scalar(0.2486832856702118)) 

```

If you just take a look at the last term ```scalar(0.2486832856702118)```, you see it will be subtracted finally by something which will definitely be zero. The reason is that only two tensors can be added or subtracted. 

To summarize again my goal of using this approach, I want to receive an equation in the following form:
```
C0T1+C1T2+C2T3+C3T4
```
C0,C1,C2,C3 are constants/scalars.
Something similar to linear regression. Is this possible with this approach?

I will put my code again here for better discussion.
my custom functions

```
def node_add(child1, child2, dims=[]):           #only two tensors will be added to each other
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.add(child1, child2)
    elif np.all(child1==0) or np.all(child2==0):
        return tf.add(child1, child2)
    else:
        return tf.constant(0,shape=dims,dtype=tf.float32)


def node_sub(child1, child2, dims=[]):          #only two tensors will be substracted
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.math.subtract(child1, child2)
    elif np.all(child1==0) or np.all(child2==0):
        return tf.math.subtract(child1, child2)
    else:
        return tf.constant(0,shape=dims,dtype=tf.float32)


def node_mult(child1, child2, dims=[]):
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.constant(0,shape=dims,dtype=tf.float32)
    elif len(tf.shape(child1))==0 and len(tf.shape(child2))==0:
        return tf.constant(0,shape=dims,dtype=tf.float32)
    else:
        return tf.convert_to_tensor(child1*child2, dtype=tf.float32) 
```

And here is the engine

```

                engine = Engine(uniform_scalar_prob=0,
                                scalar_prob=0.35,
                                terminal_prob=0.2,
                                terminal_set=my_terminal_set,
                                fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                max_tree_depth=max_tree_dep,
                                target_dims=res,
                                target=optimal_solution,
                                # elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimizing',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=3,
                                min_domain=-0.25,
                                max_domain=0.25,
                                #operators=normal_set,
                                function_set=my_function_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=False,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)

                # run evolutionary process
                engine.run()

    print("Done!")
```

**Comment by AwardOfSky** [comment]
Hello @omidr1370 . If I understood correctly what you are trying to achieve is linear regression, which can be seen as a subgroup of symbolic regression.

However, the aim of TensorGP (and GP as a whole) is to evolve populations of expressions freely without restrictions (without domain-specific knowledge about the problem).
If you wish all individuals of the population to follow the same formula, you could do it by editing the engine.py file.
However, I would first encourage you to perform a standard evolutionary run first.
If a linear formula is the most efficient way to approximate your target, then, in theory, with enough generations (and probably some parameter tweaking), evolution will lead individuals to that formula.

Then again, there are other tools specifically designed for that kind of approximation.
Sorry if this sounds discouraging, maybe I did not understand your problem fully.

**Comment by omidr1370** [comment]
Thank you @AwardOfSky for your explanation. I'll be grateful if you provide some references and codes(links if available) to those tools you mentioned? I couldn't find any method which would be useful for my tensorial input features.

**Comment by omidr1370** [comment]
Thank you again for your approach. I would like to report another problem. It seems the "optimal solution" is not working with more than two variables in the domain knowledge format(not specific target). I even checked with your own example but not working. For example, this one works:

```python
def calc_fit(**kwargs):
    # read parameters
    population = kwargs.get('population')
    generation = kwargs.get('generation')
    tensors = kwargs.get('tensors')
    f_path = kwargs.get('f_path')
    _stf = kwargs.get('stf')
    target = kwargs.get('target')

    fn = f_path + "gen_" + str(generation).zfill(5)
    fitness = []
    times = []
    best_ind = 0

    # set objective function according to min/max
    fit = 0
    condition = lambda: (fit < max_fit)  # minimizing
    max_fit = float('inf')

    for i in range(len(tensors)):

        start_ind = time.time()
        fit = tf_rmse(tensors[i], target).numpy()

        if condition():
            max_fit = fit
            best_ind = i

        times.append((time.time() - start_ind) * 1000.0)
        fitness.append(fit)
        population[i]['fitness'] = fit

    #if generation == gens:
    #    save_image(tensors[best_ind], best_ind, fn, 2)

    return population, population[best_ind]


# Different types of function sets
extended_fset = {'max', 'min', 'abs', 'add', 'and', 'or', 'mult', 'sub', 'xor', 'neg', 'cos', 'sin', 'tan', 'sqrt', 'div', 'exp', 'log', 'warp'}
simple_set = {'add', 'sub', 'mult', 'div', 'sin', 'tan', 'cos'}
normal_set = {'add', 'mult', 'sub', 'div', 'cos', 'sin', 'tan', 'abs', 'sign', 'pow'}


if __name__ == "__main__":

    # GP params
    dev = '/gpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 49  # 50
    pop_size = 50  # 50
    tour_size = 3
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 10
    max_init_depth = 10
    elite_size = 1 # 0 to turn off
    runs = 1 # Number of average runs

    # problems
    pagie = 'div(add(x, y), scalar(2))'

    problems = [pagie]  # Add to run more problems

    # Domains dimensions
    test_cases = [[64, 64]]

    for p in problems:

        for res in test_cases:

            for r in range(runs):

                #seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482 # reproducibility

                # create engine
                engine = Engine(fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                max_tree_depth=max_tree_dep,
                                target_dims=res,
                                target=pagie,
                                #elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimizing',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=2,
                                min_domain=-5,
                                max_domain=5,
                                operators=normal_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=False,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)

                # run evolutionary process
                engine.run()
```
When I change target from `pagie =div(add(x, y), scalar(2))`   to `pagie = add(div(add(x, y), scalar(2)),z)`. Bascially, adding one more variable. I receive an error. I changed the `effective_dims` from `2` to `3` but this hasn't solved the problem. So, this one is not working:

```python
def calc_fit(**kwargs):
    # read parameters
    population = kwargs.get('population')
    generation = kwargs.get('generation')
    tensors = kwargs.get('tensors')
    f_path = kwargs.get('f_path')
    _stf = kwargs.get('stf')
    target = kwargs.get('target')

    fn = f_path + "gen_" + str(generation).zfill(5)
    fitness = []
    times = []
    best_ind = 0

    # set objective function according to min/max
    fit = 0
    condition = lambda: (fit < max_fit)  # minimizing
    max_fit = float('inf')

    for i in range(len(tensors)):

        start_ind = time.time()
        fit = tf_rmse(tensors[i], target).numpy()

        if condition():
            max_fit = fit
            best_ind = i

        times.append((time.time() - start_ind) * 1000.0)
        fitness.append(fit)
        population[i]['fitness'] = fit

    #if generation == gens:
    #    save_image(tensors[best_ind], best_ind, fn, 2)

    return population, population[best_ind]


# Different types of function sets
extended_fset = {'max', 'min', 'abs', 'add', 'and', 'or', 'mult', 'sub', 'xor', 'neg', 'cos', 'sin', 'tan', 'sqrt', 'div', 'exp', 'log', 'warp'}
simple_set = {'add', 'sub', 'mult', 'div', 'sin', 'tan', 'cos'}
normal_set = {'add', 'mult', 'sub', 'div', 'cos', 'sin', 'tan', 'abs', 'sign', 'pow'}


if __name__ == "__main__":

    # GP params
    dev = '/gpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 49  # 50
    pop_size = 50  # 50
    tour_size = 3
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 10
    max_init_depth = 10
    elite_size = 1 # 0 to turn off
    runs = 1 # Number of average runs

    # problem
    pagie = 'add(div(add(x, y), scalar(2)),z)'

    problems = [pagie]  # Add to run more problems

    # Domains dimensions
    test_cases = [[64, 64]]

    for p in problems:

        for res in test_cases:

            for r in range(runs):

                #seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482 # reproducibility

                # create engine
                engine = Engine(fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                max_tree_depth=max_tree_dep,
                                target_dims=res,
                                target=pagie,
                                #elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimizing',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=3,
                                min_domain=-5,
                                max_domain=5,
                                operators=normal_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=False,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)

                # run evolutionary process
                engine.run()

```

and this is the error:
```python
Device /gpu:0 successfully tested, using this device.  
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-185-e339464dd78a> in <module>
     75 
     76                 # create engine
---> 77                 engine = Engine(fitness_func=calc_fit,
     78                                 population_size=pop_size,
     79                                 tournament_size=tour_size,

C:\TensorGP-master\tensorgp\engine.py in __init__(self, fitness_func, population_size, tournament_size, mutation_rate, mutation_funcs, mutation_probs, crossover_rate, elitism, min_tree_depth, max_tree_depth, max_init_depth, min_init_depth, method, terminal_prob, scalar_prob, uniform_scalar_prob, stop_criteria, stop_value, objective, min_domain, max_domain, const_range, effective_dims, operators, function_set, terminal_set, immigration, target_dims, target, max_nodes, seed, debug, save_graphics, show_graphics, device, save_to_file, write_log, write_gen_stats, initial_test_device, previous_state, var_func, read_init_pop_from_file)
    866             else:
    867                 self.var_func = var_func
--> 868             self.terminal = Terminal_Set(self.effective_dims, self.target_dims, engref=self, function_ptr_to_var_node=self.var_func)
    869 
    870 

C:\TensorGP-master\tensorgp\engine.py in __init__(self, effective_dim, resolution, function_ptr_to_var_node, debug, engref)
   1754         self.engref = engref
   1755         self.dimension = resolution[effective_dim] if (effective_dim < len(resolution)) else 1
-> 1756         self.set = self.make_term_variables(0, effective_dim, resolution, function_ptr_to_var_node) # x, y
   1757         self.latentset = self.make_term_variables(effective_dim, len(resolution), resolution, function_ptr_to_var_node) # z for terminal
   1758 

C:\TensorGP-master\tensorgp\engine.py in make_term_variables(self, start, end, resolution, fptr)
   1775             vari = i # TODO: ye, this is because of images, right?....
   1776             if i < 2: vari = 1 - i
-> 1777             res[name] = fptr(np.copy(resolution), vari)
   1778             #res[name] = fptr(np.copy(resolution), minval = _min_domain, maxval = _max_domain)
   1779         return res

C:\TensorGP-master\tensorgp\engine.py in resolve_var_node(dimensions, n)
     90 def resolve_var_node(dimensions, n):
     91     temp = np.ones(len(dimensions), dtype=int)
---> 92     temp[n] = -1
     93     res = tf.reshape(tf.range(dimensions[n], dtype=tf.float32), temp)
     94     _resolution = dimensions[n]

IndexError: index 2 is out of bounds for axis 0 with size 2

```
I'll be grateful if you let me know the exact problem and the solution to solve it. Thank you so much.

**Comment by omidr1370** [comment]
Hello again. Happy new year!. Sorry for reporting a lot of things and taking your time. I checked the domain knowledge option with only two defined custom variables(without x,y,..) but I receive an error. The error is different from the previous one I reported. I'll be grateful if you let me know the solution to solve this issue. Below is my code and error:

```python
def calc_fit(**kwargs):
    # read parameters
    population = kwargs.get('population')
    generation = kwargs.get('generation')
    tensors = kwargs.get('tensors')
    f_path = kwargs.get('f_path')
    _stf = kwargs.get('stf')
    target = kwargs.get('target')

    fn = f_path + "gen_" + str(generation).zfill(5)
    fitness = []
    times = []
    best_ind = 0

    # set objective function according to min/max
    fit = 0
    condition = lambda: (fit < max_fit)  # minimizing
    max_fit = float('inf')

    for i in range(len(tensors)):

        start_ind = time.time()
        fit = tf_rmse(tensors[i], target).numpy()

        if condition():
            max_fit = fit
            best_ind = i

        times.append((time.time() - start_ind) * 1000.0)
        fitness.append(fit)
        population[i]['fitness'] = fit

    #if generation == gens:
    #    save_image(tensors[best_ind], best_ind, fn, 2)

    return population, population[best_ind]


if __name__ == "__main__":

    # GP params
    dev = '/cpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 350
    pop_size = 2000
    tour_size = 2
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 3
    max_init_depth = 4
    elite_size = 1  # 0 to turn off
    runs = 1  # Number of average runs

    # problems
    indexing_variables = 3
    domain_range = [19209 , 2, 2]
    my_terminal_set = Terminal_Set(indexing_variables, domain_range)
    my_terminal_set.add_to_set("T_1", tf.convert_to_tensor(T_1, tf.float32))
    my_terminal_set.add_to_set("T_2", tf.convert_to_tensor(T_2, tf.float32))


    optimal_solution = 'add(mult(neg(T_1), 0.01), mult(T_2, 0.1))'
    my_terminal_set.remove_from_set("x")
    my_terminal_set.remove_from_set("y")
    my_terminal_set.remove_from_set("z")

    normal_set = {'add', 'sub', 'mult','neg'}

    problems = [optimal_solution]  # Add to run more problems

    # Domains dimensions
    test_cases = [[19209 , 2, 2]]

    for p in problems:

        for res in test_cases:

            for r in range(runs):
                # seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482  # reproducibility

                # create engine
                engine = Engine(uniform_scalar_prob=0.5,
                                scalar_prob=0.55,
                                terminal_prob=0.2,
                                terminal_set=my_terminal_set,
                                fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                min_tree_depth=3,
                                max_tree_depth=4,
                                target_dims=res,
                                target=optimal_solution,
                                # elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimization',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=3,
                                min_domain=-0.25,
                                max_domain=0.25,
                                operators=normal_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=False,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)
                # run evolutionary process
                engine.run()

    print("Done!")

```

Error

```python

Device /cpu:0 successfully tested, using this device.  
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-137-7071a6643839> in <module>
     80 
     81                 # create engine
---> 82                 engine = Engine(uniform_scalar_prob=0.5,
     83                                 scalar_prob=0.55,
     84                                 terminal_prob=0.2,

C:\TensorGP-master\tensorgp\engine.py in __init__(self, fitness_func, population_size, tournament_size, mutation_rate, mutation_funcs, mutation_probs, crossover_rate, elitism, min_tree_depth, max_tree_depth, max_init_depth, min_init_depth, method, terminal_prob, scalar_prob, uniform_scalar_prob, stop_criteria, stop_value, objective, min_domain, max_domain, const_range, effective_dims, operators, function_set, terminal_set, immigration, target_dims, target, max_nodes, seed, debug, save_graphics, show_graphics, device, save_to_file, write_log, write_gen_stats, initial_test_device, previous_state, var_func, read_init_pop_from_file)
    873         if isinstance(target, str):
    874             target = 'mult(scalar(127.5), ' + target + ')'
--> 875             _, tree = str_to_tree(target, self.terminal.set, constrain_domain=False)
    876 
    877             with tf.device(self.device):

C:\TensorGP-master\tensorgp\engine.py in str_to_tree(stree, terminal_set, constrain_domain)
    364 # just a wrapper for different expression types and strip preprocessing
    365 def str_to_tree(stree, terminal_set, constrain_domain=True):
--> 366     return str_to_tree_normal(stree.strip() + "", terminal_set, 0, constrain_domain)
    367 
    368 

C:\TensorGP-master\tensorgp\engine.py in str_to_tree_normal(stree, terminal_set, number_nodes, constrain_domain)
    397                 last_pos = i + 2
    398 
--> 399         number_nodes, tree = str_to_tree_normal(args[last_pos:], terminal_set, number_nodes, constrain_domain)
    400         children.append(tree)
    401         if primitive == "if":

C:\TensorGP-master\tensorgp\engine.py in str_to_tree_normal(stree, terminal_set, number_nodes, constrain_domain)
    393                 pc -= 1
    394             elif c == ',' and pc == 0:
--> 395                 number_nodes, tree = str_to_tree_normal(args[last_pos:i], terminal_set, number_nodes, constrain_domain)
    396                 children.append(tree)
    397                 last_pos = i + 2

C:\TensorGP-master\tensorgp\engine.py in str_to_tree_normal(stree, terminal_set, number_nodes, constrain_domain)
    397                 last_pos = i + 2
    398 
--> 399         number_nodes, tree = str_to_tree_normal(args[last_pos:], terminal_set, number_nodes, constrain_domain)
    400         children.append(tree)
    401         if primitive == "if":

C:\TensorGP-master\tensorgp\engine.py in str_to_tree_normal(stree, terminal_set, number_nodes, constrain_domain)
    381         if x[0][0] == '_':
    382             primitive = x[0][1::]
--> 383         args = x[1]
    384         pc = 0
    385         last_pos = 0

IndexError: list index out of range


```

**Comment by AwardOfSky** [comment]
Hello @omidr1370. Happy new year!

Again, sorry for not addressing your issues sooner, but now in Christmas and New Year I haven't been so active. I hope you understand.
In regards to the tools for linear regression I know that modules such as sklearn provide good support for linear regression tasks, if that is solely what you want to do. Again, I don't know much about their support for tensors.

Regarding your second issue, the problem you are having is related to the dimensions, You define a target with three variables, yet the evaluation domain you define only has two dimensions:

Try changing this:

```Python
pagie = 'add(div(add(x, y), scalar(2)),z)'
problems = [pagie]  # Add to run more problems

# Domains dimensions
test_cases = [[64, 64]]
```

To something like this:

```Python
pagie = 'add(div(add(x, y), scalar(2)),z)'
problems = [pagie]  # Add to run more problems

# Domains dimensions
test_cases = [[64, 64, 3]]
```
I put 3 as an example, If you want to emulate RGB (3) channels, for example, but it can have whatever value, as long as your tensors fit in memory.

Regarding your last issue, you need to call the scalar function to define tensor scalars (you gave an idea tho: maybe I should add a feature to introduce these automatically). Try replacing this `add(mult(neg(T_1), 0.01), mult(T_2, 0.1))` with `add(mult(neg(T_1), scalar(0.01)), mult(T_2, scalar(0.1)))`.

I must confess that because of the errors I saw in the code I am diagnosing these problems without compiling the actual code you provide, so if you still have issues after these suggestions do not hesitate in getting back to me and I will provide a working code.

**Comment by omidr1370** [comment]
Thank you so much for your reply. Yes, all of the things you suggested solved the issues. Actually, I received better results in this format(without defining the target) and it's near to what I want. However, there are still some minor problems. Now, I want to report two other issues. The first one happens when I am increasing variables to more than 2 and using the predefined operators. For example, this one works fine with only T_1 and T_2:

```python
def calc_fit(**kwargs):
    # read parameters
    population = kwargs.get('population')
    generation = kwargs.get('generation')
    tensors = kwargs.get('tensors')
    f_path = kwargs.get('f_path')
    _stf = kwargs.get('stf')
    target = kwargs.get('target')

    fn = f_path + "gen_" + str(generation).zfill(5)
    fitness = []
    times = []
    best_ind = 0

    # set objective function according to min/max
    fit = 0
    condition = lambda: (fit < max_fit)  # minimizing
    max_fit = float('inf')

    for i in range(len(tensors)):

        start_ind = time.time()
        fit = tf_rmse(tensors[i], target).numpy()

        if condition():
            max_fit = fit
            best_ind = i

        times.append((time.time() - start_ind) * 1000.0)
        fitness.append(fit)
        population[i]['fitness'] = fit

    #if generation == gens:
    #    save_image(tensors[best_ind], best_ind, fn, 2)

    return population, population[best_ind]


if __name__ == "__main__":

    # GP params
    dev = '/cpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 350
    pop_size = 2000
    tour_size = 2
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 3
    max_init_depth = 4
    elite_size = 1  # 0 to turn off
    runs = 1  # Number of average runs

    # problems
    indexing_variables = 3
    domain_range = [3861, 2, 2]
    my_terminal_set = Terminal_Set(indexing_variables, domain_range)
    my_terminal_set.add_to_set("T_1", tf.convert_to_tensor(T_1, tf.float32))
    my_terminal_set.add_to_set("T_2", tf.convert_to_tensor(T_2, tf.float32))

    optimal_solution = 'add(mult(neg(T_1), scalar(0.01)), mult(T_2, scalar(0.1)))'
    my_terminal_set.remove_from_set("x")
    my_terminal_set.remove_from_set("y")
    my_terminal_set.remove_from_set("z")



    normal_set = {'add', 'sub', 'mult','neg'}

    problems = [optimal_solution]  # Add to run more problems

    # Domains dimensions
    test_cases = [[3861, 2, 2]]

    for p in problems:

        for res in test_cases:

            for r in range(runs):
                # seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482  # reproducibility

                # create engine
                engine = Engine(uniform_scalar_prob=0.5,
                                scalar_prob=0.55,
                                terminal_prob=0.2,
                                terminal_set=my_terminal_set,
                                fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                min_tree_depth=3,
                                max_tree_depth=4,
                                target_dims=res,
                                target=optimal_solution,
                                # elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimization',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=3,
                                min_domain=-0.25,
                                max_domain=0.25,
                                operators=normal_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=False,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)
                # run evolutionary process
                engine.run()

    print("Done!")

```

However, this one is not working. I just added T_3 :

```python
def calc_fit(**kwargs):
    # read parameters
    population = kwargs.get('population')
    generation = kwargs.get('generation')
    tensors = kwargs.get('tensors')
    f_path = kwargs.get('f_path')
    _stf = kwargs.get('stf')
    target = kwargs.get('target')

    fn = f_path + "gen_" + str(generation).zfill(5)
    fitness = []
    times = []
    best_ind = 0

    # set objective function according to min/max
    fit = 0
    condition = lambda: (fit < max_fit)  # minimizing
    max_fit = float('inf')

    for i in range(len(tensors)):

        start_ind = time.time()
        fit = tf_rmse(tensors[i], target).numpy()

        if condition():
            max_fit = fit
            best_ind = i

        times.append((time.time() - start_ind) * 1000.0)
        fitness.append(fit)
        population[i]['fitness'] = fit

    #if generation == gens:
    #    save_image(tensors[best_ind], best_ind, fn, 2)

    return population, population[best_ind]


if __name__ == "__main__":

    # GP params
    dev = '/cpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 350
    pop_size = 2000
    tour_size = 2
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 3
    max_init_depth = 4
    elite_size = 1  # 0 to turn off
    runs = 1  # Number of average runs

    # problems
    indexing_variables = 3
    domain_range = [3861, 2, 2]
    my_terminal_set = Terminal_Set(indexing_variables, domain_range)
    my_terminal_set.add_to_set("T_1", tf.convert_to_tensor(T_1, tf.float32))
    my_terminal_set.add_to_set("T_2", tf.convert_to_tensor(T_2, tf.float32))
    my_terminal_set.add_to_set("T_3", tf.convert_to_tensor(T_3, tf.float32))

    optimal_solution = 'add(add(mult(neg(T_1), scalar(0.01)), mult(T_2, scalar(0.1))),mult(T_3, scalar(0.1)))'
    my_terminal_set.remove_from_set("x")
    my_terminal_set.remove_from_set("y")
    my_terminal_set.remove_from_set("z")



    normal_set = {'add', 'sub', 'mult','neg'}

    problems = [optimal_solution]  # Add to run more problems

    # Domains dimensions
    test_cases = [[3861, 2, 2]]

    for p in problems:

        for res in test_cases:

            for r in range(runs):
                # seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482  # reproducibility

                # create engine
                engine = Engine(uniform_scalar_prob=0.5,
                                scalar_prob=0.55,
                                terminal_prob=0.2,
                                terminal_set=my_terminal_set,
                                fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                min_tree_depth=3,
                                max_tree_depth=4,
                                target_dims=res,
                                target=optimal_solution,
                                # elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimization',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=3,
                                min_domain=-0.25,
                                max_domain=0.25,
                                operators=normal_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=False,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)
                # run evolutionary process
                engine.run()

    print("Done!")

```

Error:
```python
Device /cpu:0 successfully tested, using this device.  
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-133-211ea913c31c> in <module>
     82 
     83                 # create engine
---> 84                 engine = Engine(uniform_scalar_prob=0.5,
     85                                 scalar_prob=0.55,
     86                                 terminal_prob=0.2,

C:\TensorGP-master\tensorgp\engine.py in __init__(self, fitness_func, population_size, tournament_size, mutation_rate, mutation_funcs, mutation_probs, crossover_rate, elitism, min_tree_depth, max_tree_depth, max_init_depth, min_init_depth, method, terminal_prob, scalar_prob, uniform_scalar_prob, stop_criteria, stop_value, objective, min_domain, max_domain, const_range, effective_dims, operators, function_set, terminal_set, immigration, target_dims, target, max_nodes, seed, debug, save_graphics, show_graphics, device, save_to_file, write_log, write_gen_stats, initial_test_device, previous_state, var_func, read_init_pop_from_file)
    877             with tf.device(self.device):
    878                 #self.target = self.final_transform_domain(tree.get_tensor(self))
--> 879                 self.target = tf.cast(tree.get_tensor(self), tf.float32) # cast to an int tensor
    880                 #self.target = pagie_poly(self.terminal.set, self.target_dims)
    881         else:

C:\TensorGP-master\tensorgp\engine.py in get_tensor(self, engref)
    310             tens_list = []
    311             for c in self.children:
--> 312                 tens_list.append(c.get_tensor(engref))
    313 
    314             return self.node_tensor(tens_list, engref)

C:\TensorGP-master\tensorgp\engine.py in get_tensor(self, engref)
    310             tens_list = []
    311             for c in self.children:
--> 312                 tens_list.append(c.get_tensor(engref))
    313 
    314             return self.node_tensor(tens_list, engref)

C:\TensorGP-master\tensorgp\engine.py in get_tensor(self, engref)
    312                 tens_list.append(c.get_tensor(engref))
    313 
--> 314             return self.node_tensor(tens_list, engref)
    315 
    316     def get_str(self):

C:\TensorGP-master\tensorgp\engine.py in node_tensor(self, tens, engref)
    270     def node_tensor(self, tens, engref):
    271 
--> 272         arity = engref.function.set[self.value][0]
    273         if self.value != 'warp':
    274             arg_list = tens[:arity]

KeyError: 'ult'

```

Another problem happens when I am trying to use custom operators

```python

def calc_fit(**kwargs):
    # read parameters
    population = kwargs.get('population')
    generation = kwargs.get('generation')
    tensors = kwargs.get('tensors')
    f_path = kwargs.get('f_path')
    _stf = kwargs.get('stf')
    target = kwargs.get('target')

    fn = f_path + "gen_" + str(generation).zfill(5)
    fitness = []
    times = []
    best_ind = 0

    # set objective function according to min/max
    fit = 0
    condition = lambda: (fit < max_fit)  # minimizing
    max_fit = float('inf')

    for i in range(len(tensors)):

        start_ind = time.time()
        fit = tf_rmse(tensors[i], target).numpy()

        if condition():
            max_fit = fit
            best_ind = i

        times.append((time.time() - start_ind) * 1000.0)
        fitness.append(fit)
        population[i]['fitness'] = fit

    #if generation == gens:
    #    save_image(tensors[best_ind], best_ind, fn, 2)

    return population, population[best_ind]




def node_add(child1, child2, dims=[]):           #only two tensors will be added to each other
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.add(child1, child2)
    elif (np.all(child1==0) or np.all(child2==0)) and (len(tf.shape(child1))==0 and len(tf.shape(child2))==0):
        return tf.constant(0,shape=dims,dtype=tf.float32)
    elif (np.all(child1==0) or np.all(child2==0)) and (len(tf.shape(child1))==3 and len(tf.shape(child2))==0):
        return tf.add(child1, child2)
    elif (np.all(child1==0) or np.all(child2==0)) and (len(tf.shape(child1))==0 and len(tf.shape(child2))==3):
        return tf.convert_to_tensor(child2, tf.float32)
    else:
        return tf.constant(0,shape=dims,dtype=tf.float32)


def node_sub(child1, child2, dims=[]):          #only two tensors will be substracted
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.math.subtract(child1, child2)
    elif (np.all(child1==0) or np.all(child2==0)) and (len(tf.shape(child1))==0 and len(tf.shape(child2))==0):
        return tf.constant(0,shape=dims,dtype=tf.float32)
    elif (np.all(child1==0) or np.all(child2==0)) and (len(tf.shape(child1))==3 and len(tf.shape(child2))==0):
        return tf.math.subtract(child1, child2)
    elif (np.all(child1==0) or np.all(child2==0)) and (len(tf.shape(child1))==0 and len(tf.shape(child2))==3):
        return tf.convert_to_tensor(-child2, tf.float32)
    else:
        return tf.constant(0,shape=dims,dtype=tf.float32)


def node_mult(child1, child2, dims=[]):
    if len(tf.shape(child1))==3 and len(tf.shape(child2))==3:
        return tf.constant(0,shape=dims,dtype=tf.float32)
    elif len(tf.shape(child1))==0 and len(tf.shape(child2))==0:
        return tf.constant(0,shape=dims,dtype=tf.float32)
    else:
        return tf.convert_to_tensor(child1*child2, dtype=tf.float32) 

def node_neg(child1, dims=[]):
    return tf.math.negative(child1)




if __name__ == "__main__":

    # GP params
    dev = '/cpu:0'  # device to run, write '/cpu_0' to tun on cpu
    gens = 350
    pop_size = 2000
    tour_size = 2
    mut_rate = 0.1
    cross_rate = 0.9
    max_tree_dep = 3
    max_init_depth = 4
    elite_size = 1  # 0 to turn off
    runs = 1  # Number of average runs

    # problems
    indexing_variables = 3
    domain_range = [3861, 2, 2]
    my_terminal_set = Terminal_Set(indexing_variables, domain_range)
    my_terminal_set.add_to_set("T_1", tf.convert_to_tensor(T_1, tf.float32))
    my_terminal_set.add_to_set("T_2", tf.convert_to_tensor(T_2, tf.float32))



    optimal_solution = 'node_add(node_mult(node_neg(T_1), scalar(0.01)), node_mult(T_2, scalar(0.1)))'
    my_terminal_set.remove_from_set("x")
    my_terminal_set.remove_from_set("y")
    my_terminal_set.remove_from_set("z")

    
    
    # Define subset of internally implemented operators
    primitives = {'add', 'sub', 'mult', 'div'}
    my_function_set = Function_Set(primitives, indexing_variables)

    # Add rmse_node, which has 2 arguments with name "rmse"
    my_function_set.add_to_set("node_add", 2, node_add)
    my_function_set.add_to_set("node_sub", 2, node_sub)
    my_function_set.add_to_set("node_mult", 2, node_mult)
    my_function_set.add_to_set("node_neg", 1, node_neg)

    # You can also remove operators from the set
    my_function_set.remove_from_set("add")
    my_function_set.remove_from_set("sub")
    my_function_set.remove_from_set("mult")
    my_function_set.remove_from_set("div")


    #normal_set = {'add', 'sub', 'mult','neg'}

    problems = [optimal_solution]  # Add to run more problems

    # Domains dimensions
    test_cases = [[3861, 2, 2]]

    for p in problems:

        for res in test_cases:

            for r in range(runs):
                # seeds = random.randint(0, 0x7fffffff)
                seeds = 39485793482  # reproducibility

                # create engine
                engine = Engine(uniform_scalar_prob=0.5,
                                scalar_prob=0.55,
                                terminal_prob=0.2,
                                terminal_set=my_terminal_set,
                                fitness_func=calc_fit,
                                population_size=pop_size,
                                tournament_size=tour_size,
                                mutation_rate=mut_rate,
                                crossover_rate=cross_rate,
                                min_tree_depth=3,
                                max_tree_depth=4,
                                target_dims=res,
                                target=optimal_solution,
                                # elitism=elite_size,
                                method='ramped half-and-half',
                                max_init_depth=max_init_depth,
                                objective='minimization',
                                device=dev,
                                stop_criteria='generation',
                                stop_value=gens,
                                effective_dims=3,
                                min_domain=-0.25,
                                max_domain=0.25,
                                operators=my_function_set,
                                #operators=normal_set,
                                seed=seeds,
                                save_to_file=10,
                                save_graphics=False,
                                show_graphics=False,
                                write_log=False,
                                write_gen_stats=False,
                                read_init_pop_from_file=None)
                # run evolutionary process
                engine.run()

    print("Done!")

```
Error:

```python

Device /cpu:0 successfully tested, using this device.  
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-132-309d389c9542> in <module>
    142 
    143                 # create engine
--> 144                 engine = Engine(uniform_scalar_prob=0.5,
    145                                 scalar_prob=0.55,
    146                                 terminal_prob=0.2,

C:\TensorGP-master\tensorgp\engine.py in __init__(self, fitness_func, population_size, tournament_size, mutation_rate, mutation_funcs, mutation_probs, crossover_rate, elitism, min_tree_depth, max_tree_depth, max_init_depth, min_init_depth, method, terminal_prob, scalar_prob, uniform_scalar_prob, stop_criteria, stop_value, objective, min_domain, max_domain, const_range, effective_dims, operators, function_set, terminal_set, immigration, target_dims, target, max_nodes, seed, debug, save_graphics, show_graphics, device, save_to_file, write_log, write_gen_stats, initial_test_device, previous_state, var_func, read_init_pop_from_file)
    855             self.function = function_set
    856         else:
--> 857             self.function = Function_Set(operators, self.effective_dims, debug = self.debug)
    858         if isinstance(terminal_set, Terminal_Set):
    859             self.terminal = terminal_set

C:\TensorGP-master\tensorgp\engine.py in __init__(self, fset, edim, debug)
   1698         if fset is None:
   1699             fset = set(self.operators_def.keys())
-> 1700         fset = sorted(fset)
   1701 
   1702         for e in fset:

TypeError: 'Function_Set' object is not iterable

```

Again, I am really thankful for your patience and help.

**Comment by AwardOfSky** [comment]
Hello @omidr1370.
The first issue you mention has to do with a lack of space in the function you defined. That should however not happen as I replaced the whitespace before the parsing. There was a bug in the str_to_tree functions. It is fixed now, you should be able to omit spaces at your will. Thanks for reporting.

Regarding your second issue, it concerns the fact that you are using the `operators` argument instead of the `function_set` argument. When you have a list of existing operators you want to use, you use the operators, for instance:

```Python
simple_set = {'add', 'sub', 'mult', 'div'}
engine = Engine( ... operators=simple_set, ...)
```

In your case your building the function set from the ground up by adding and removing operators and so you should define it like:

```Python
engine = Engine( ... function_set=my_function_set, ...)
```

Btw, to avoid other types of old bugs, I would strongly encourage you to use the "tf2.7" branch. I will eventually make that branch the main one because many things are different in older TF versions and it is too costly to fix every bug in every version.
The only thing to change for that branch that concerns the user is the fitness function branch: the best index is returned instead  of the corresponding individual.
You should change the last line of the fitness function from:

```Python
    return population, population[best_ind]
```

to 

```Python
    return population, best_ind
```

if you are to use the "tf2.7" branch.
